# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamsgroup', '0003_events_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='cover',
            field=models.CharField(default='img/', max_length=500),
        ),
        migrations.AddField(
            model_name='school',
            name='cover',
            field=models.CharField(default='img/', max_length=500),
        ),
    ]
