# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamsgroup', '0004_auto_20160823_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('college', models.IntegerField()),
                ('content', models.CharField(blank=True, max_length=5000)),
                ('image', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
