# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamsgroup', '0006_auto_20160823_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
