# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=16)),
                ('phno', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=6)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
