# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='college',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='school',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
